name = "RIXSCalculator_dev_electrons"
uuid = "6494946e-c796-40c0-bcb4-96b885e21a6e"
authors = ["Jan Attig <jattig@thp.Uni-Koeln.DE>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
